### ISSUE TITLE
IBD computation without pedigree

### ISSUE THREAD

**Issue by evakoe** [markabney/Kinpute#2]
One of the strengths of kinpute is that no pedigree is required. However, IBDLD, that you recommend for generating the mandatory IBD information, does require a pedigree. Do you have a suggestion of how to generate IBD information for kinpute without a pedigree file?

Thank you
Eva

**Comment by markabney** [comment]
A pedigree is optional for IBDLD. On the IBDLD command line use "-method
GIBDLD" to do computations not using a pedigree. Note that because we use
plink (or plink-like) input file formats (e.g. *.ped), there are columns
for pedigree information. This information, however, is ignored by IBDLD.

**Comment by evakoe** [comment]
I see, thank you.
